jid: upload.yourdomain.tld
secret: yoursecret
storage_path : ./
whitelist:
  - yourdomain.tld
  - someotherdomain.tld
max_file_size: 20971520 #20MiB
http_address: 127.0.0.1 #use 0.0.0.0 if you don't want to use a proxy
http_port: 8080
get_url : http://upload.yoursite.tld:8080
put_url : http://upload.yoursite.tld:8080
