jid: upload.siacs.eu
secret: something
storage_path : ./
whitelist:
  - jabber.ccc.de
  - siacs.eu
  - gultsch.de
max_file_size: 20971520 #20MiB
http_address: 127.0.0.1
http_port: 8080
get_url : http://upload.siacs.eu:8080
put_url : http://upload.siacs.eu:8080
